apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-tekton-sample
spec:
  destination:
    namespace: myapp
    server: 'https://kubernetes.default.svc'
  source:
    path: knative
    repoURL: 'https://github.com/Lucifergene/go-tekton-sample-config'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
