apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello
spec:
  template:
    metadata:
      creationTimestamp: null
      name: hello-world-e817210a97c9fac12053df2bbc32f5e35ebcf77f
    spec:
      containerConcurrency: 0
      containers:
        - image: docker.io/avik6028/go-tekton-sample:c6e578a7a2ad8b122e75b96b860865ed94d6d4b2
          name: user-container
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
