apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello
spec:
  template:
    metadata:
      creationTimestamp: null
      name: hello-world-9360752bdc7d78073470d9ca2218afbe1a36e4cf
    spec:
      containerConcurrency: 0
      containers:
        - image: docker.io/avik6028/go-tekton-sample:9360752bdc7d78073470d9ca2218afbe1a36e4cf
          name: user-container
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
