apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello
spec:
  template:
    metadata:
      creationTimestamp: null
      name: hello-world-00e204a88d1fe90d60c710bab70a677adffee8a7
    spec:
      containerConcurrency: 0
      containers:
        - image: docker.io/avik6028/go-tekton-sample:00e204a88d1fe90d60c710bab70a677adffee8a7
          name: user-container
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
