apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello
spec:
  template:
    metadata:
      creationTimestamp: null
      name: hello-world-8a6ccbcd577ebf55e4991f512e791ca5948acaab
    spec:
      containerConcurrency: 0
      containers:
        - image: docker.io/avik6028/go-tekton-sample:8a6ccbcd577ebf55e4991f512e791ca5948acaab
          name: user-container
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
